version: '3.9'

#networks:
#  dev_network:

services:

  postgresql-diploma:
    image: postgres:14.3-alpine3.16
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234_secret
      POSTGRES_DB: ordershub_db
    container_name: postgresql-diploma-container
  #    networks:
  #      dev_network:
  #        aliases:
  #          - db-postgre

  redis-d:
    image: redis:7.0.0-alpine3.15
    ports:
      - "6379:6379"
    # depends_on:
    #   - postgresql-diploma
    container_name: redis-diploma
  #    networks:
  #      dev_network:
  #        aliases:
  #          - db-redis

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    container_name: redis-commander
  