# примеры API-запросов

@baseUrl = http://127.0.0.1:8000



# register account
###
POST {{baseUrl}}/api/v1/user/register
Content-Type: application/json

{
    "email": "archimage@yandex.com",
    "password": "87654321EEEE.ONE",
    "first_name": "igor",
    "last_name": "potakhin",
    "company": "c1",
    "position": "p1",
    "type": "shop"
}

# confirm account
###
POST {{baseUrl}}/api/v1/user/register/confirm
Content-Type: application/json

{
    "token": "41db7734e446d25fa91b3215ea45b56e8833e5724050a3",
    "email": "archimage@yandex.com"
}

# user login
###
POST {{baseUrl}}/api/v1/user/login
Content-Type: application/json

{
    "email": "archimage@yandex.com",
    "password": "87654321EEEE.ONE"
}

# got token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

# test token
###
# POST {{baseUrl}}/api/v1/user/auth
GET {{baseUrl}}/api/v1/user/auth
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{
    "email": "archimage@yandex.com",
    "password": "87654321EEEE.ONE"
}

# get account details
###
GET {{baseUrl}}/api/v1/user/details
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{
    "email": ""
}

# change account details (post method)
###
POST {{baseUrl}}/api/v1/user/details
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{
    "email": "archimage@yandex.lol",
    "password": "11111111!",
    "first_name": "egor",
    "last_name": "obtakhin",
    "company": "google",
    "position": "lead dev"
}

# get contacts
###
GET {{baseUrl}}/api/v1/user/contact
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{
}

# add new contact
###
POST {{baseUrl}}/api/v1/user/contact
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{
    "city": "ptz",
    "street": "lenina2",
    "phone": "+792162317712"
}

# remove contact
###
DELETE {{baseUrl}}/api/v1/user/contact
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{
    "items": "9,10,8"
}

# password reset test
###
POST {{baseUrl}}/api/v1/user/password_reset
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{
    "email": "archimage@yandex.ru"
}

# password reset confirm
###
POST {{baseUrl}}/api/v1/user/password_reset/confirm
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{
    "token": "de89642c7228df1",
    "password": "11131313E"
}

# partner update via link
###
POST {{baseUrl}}/api/v1/partner/update
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{
    "url": "https://raw.githubusercontent.com/archimage-wiz/Python_Diploma/master/data/shop1.yaml"
}

# partner get state
###
GET {{baseUrl}}/api/v1/partner/state
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{
}

# partner update state
###
POST {{baseUrl}}/api/v1/partner/state
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{
    "state": "True"
}

# partner orders
###
GET {{baseUrl}}/api/v1/partner/orders
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{   
}

# view category
###
GET {{baseUrl}}/api/v1/categories/
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{   
}

# view shops
###
GET {{baseUrl}}/api/v1/shops/
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{   
}

# view products
###
GET {{baseUrl}}/api/v1/products/?shop_id=3
Content-Type: application/json

{       
}


# basket retrieve
###
GET {{baseUrl}}/api/v1/basket
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{       
}


# basket add to basket 
###
POST {{baseUrl}}/api/v1/basket
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{
    "items": [
        {
            "product_info": 13,
            "quantity": 6
        }
    ]
}

# basket update in basket 
###
PUT {{baseUrl}}/api/v1/basket
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{
    "items": [
        {
            "id": 14,
            "quantity": 1
        }
    ]
}

# basket delete from basket 
###
DELETE {{baseUrl}}/api/v1/basket
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{
    "items": "14,13"
}

# orders get
###
GET {{baseUrl}}/api/v1/order
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{
    "items": "14,13"
}

# order PUT FROM BASKET TO ORDER
###
POST {{baseUrl}}/api/v1/order
Content-Type: application/json
Authorization: Token b6ad9a3e1bd6fddbff935cb7e1921997d8ffae82

{
    "id": "4",
    "contact": "1"
}

# check task status is complete
###
GET {{baseUrl}}/api/v1/task?task_id=cf6dcfc7-3a81-4acc-b68c-b3c50752f3db
Content-Type: application/json
Authorization: Token 1ac12613183f8bcdb38d59ce1ef44560c8a802fa

{
    
}