# примеры API-запросов

@baseUrl = http://127.0.0.1:8000




###
POST {{baseUrl}}/api/v1/api-token-auth
Content-Type: application/json

{
    "username": "username1",
    "password": "111"
}

###
POST {{baseUrl}}/api/v1/user/auth/reg/
Content-Type: application/json

{
    "email": "test@user.com",
    "password": "111"
}


###
POST {{baseUrl}}/api/v1/user/auth/auth/
Content-Type: application/json

{
    "email": "test@user.com",
    "password": "111"
}

###
POST {{baseUrl}}/api/v1/user/auth/test/
Content-Type: application/json
Authorization: Token 3846ec306d6a5fc845d7470e6a36049f03b47fb5

{
    "somedata": "1"
}

###
POST {{baseUrl}}/api/v1/token/
Content-Type: application/json

{
    "email": "test@user.com",
    "password": "111"
}
###
POST {{baseUrl}}/api/v1/token/verify/
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjg5MTYwMDI5LCJpYXQiOjE2ODkxNTk3MjksImp0aSI6IjliMDFjYTgwZGQwMDRiMmViOTIwYTBjYzZiNGUwOGQ2IiwidXNlcl9pZCI6MX0.pKjIGH64ZT9LxxYGBhMwrb-ijqc2YLsrEteWFLeiuSU",
    "password": "111"
}
###
POST {{baseUrl}}/api/v1/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY4OTI0NjA3MywiaWF0IjoxNjg5MTU5NjczLCJqdGkiOiI5ODYxYjc4Njk2Y2Y0NzU1ODBiZmIxMzQ0N2RmYzlmOSIsInVzZXJfaWQiOjF9.UwelVn7E1Gyz9xRGm9Kt7zBfveON6l0dVMKlHNRLU_c"
}


###
POST {{baseUrl}}/api/v1/partner-update/
Content-Type: application/json
Authorization: Token 3846ec306d6a5fc845d7470e6a36049f03b47fb5

{
    "url": "https://raw.githubusercontent.com/archimage-wiz/Python_Diploma/master/data/shop1.yaml"
}


###
GET {{baseUrl}}/api/v1/products/?shop_id=2&category_id=224
Content-Type: application/json
###
GET {{baseUrl}}/api/v1/shops/
Content-Type: application/json
###
GET {{baseUrl}}/api/v1/category/
Content-Type: application/json
###
GET {{baseUrl}}/api/v1/order/
Content-Type: application/json
Authorization: Token 3846ec306d6a5fc845d7470e6a36049f03b47fb5


# register account
###
POST {{baseUrl}}/api/v1/user/register/
Content-Type: application/json

{
    "email": "archimage@yandex.com",
    "password": "87654321EEEE.ONE",
    "first_name": "igor",
    "last_name": "potakhin",
    "company": "c1",
    "position": "p1"
}

# confirm account
###
POST {{baseUrl}}/api/v1/user/register/confirm/
Content-Type: application/json

{
    "token": "e4b99860b6e",
    "email": "archimage@yandex.com"
}
